### PR TITLE
Conform the sample light resource to binary switch

### PR DESCRIPTION
**Pull request by bgiori**
This conforms the sample light resource in the bleprph_oic
sample app to the binary switch resource type as defined
in the OCF Resource Type Spec:

https://openconnectivity.org/draftspecs/OCF_Resource_Type_Specification_v1.0.0.pdf

### CODE REVIEW

**Comment by bgiori** [comment]
This will allow people to use the android sensors_test app with a device running bleprph_oic without having to modify the code.

**Comment by mkiiskila** [comment]
This should be ok.
Do you also want to change the write handler to use POST instead of current PUT?

**Comment by bgiori** [comment]
That would conform better but the sensors test app uses put, and uploading a new app to the store for such a small change is not worth the effort involved. My concern is more that the two work out of the box rather than conformity.

**Comment by mkiiskila** [comment]
How about support both?
i.e. add
oc_resource_set_request_handler(res, OC_POST, app_set_light);
after setting the handler for OC_PUT

**Pull request merged**
