### PR TITLE
net/oic; call get routine for notifications individually for every observer. 

### PR DESCRIPTION
**Pull request by mkiiskila**
This allows for per-observer type actions/filtering.

### CODE REVIEW

**Comment by bgiori** [comment]
```
Error: repos/apache-mynewt-core/net/oic/src/messaging/coap/observe.c: In function 'coap_notify_observers':
repos/apache-mynewt-core/net/oic/src/messaging/coap/observe.c:218:27: error: unused variable 'req' [-Werror=unused-variable]
     struct coap_packet_rx req[1];
                           ^~~
cc1: all warnings being treated as errors
```

**Comment by vrahane** [comment]
@bgiori on line 224, add `(void)req` to the code. that should resolve the build issue you are having.

**Comment by bgiori** [comment]
@vrahane I fixed it using:

```
#if MYNEWT_VAL(OC_SEPARATE_RESPONSES)
    struct coap_packet_rx req[1];
#endif
```

**Comment by mkiiskila** [comment]
Thanks for checking this. Pushed a commit here which fixes build with OC_SEPARATE_RESPONSES disabled.

**Pull request merged**
