### PR TITLE
Updating to NRFX 1.7.1

### PR DESCRIPTION
**Pull request by alvarop**
I want to use the NRF52811 :D
Mynewt currently has the nrfx v1.4.0 library, which does not have the required files.

### CODE REVIEW

**Comment by mlaz** [comment]
It looks good, as far as my testing goes (ADC and PWM on nRF52832) everything is ok. Sill need to test I2C and SPI but since I don't see any significant changes which might affect these two drivers.

**Comment by mlaz** [comment]
> I did notice one error that doesn't seem to get caught by the tests.
> 
> ```
> Error: In file included from repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/nrfx.h:37,
>                  from repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/src/nrfx_gpiote.c:31:
> repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/hal/nrf_gpio.h:46:24: error: expected declaration specifiers or '...' before '(' token
>  #define NUMBER_OF_PINS (P0_PIN_NUM)
>                         ^
> repos/apache-mynewt-core/hw/mcu/nordic/include/nrfx_glue.h:69:54: note: in definition of macro 'NRFX_STATIC_ASSERT'
>  #define NRFX_STATIC_ASSERT(expression) STATIC_ASSERT(expression)
>                                                       ^~~~~~~~~~
> repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/drivers/src/nrfx_gpiote.c:51:20: note: in expansion of macro 'NUMBER_OF_PINS'
>  NRFX_STATIC_ASSERT(NUMBER_OF_PINS <= (1 << SENSE_FIELD_POS));
>                     ^~~~~~~~~~~~~~
> ```
> 
> As far as I understand, STATIC_ASSERT is a C11 feature and we're compiling with C99, no?
> Commenting that line out or #defining NRFX_STATIC_ASSERT to nothing both work, but I'm not sure what the preferred method is.

@alvarop How are you getting this? I am building all my tests locally without any problems.

**Comment by alvarop** [comment]
@mlaz It only happens on my new nrf52811 project of course :-/

**Comment by mlaz** [comment]
I talked with @alvarop on slack and we agreed to have nrf52811 support coming in on a separate PR.

**Comment by andrewleech** [comment]
Hi, I've just run into the same `NRFX_STATIC_ASSERT` issue when trying to build (my first) mynewt project for nrf52810.

There's already two copies of the `nrfx_glue.h` file that define this, the failing one used above in 
`repos/apache-mynewt-core/hw/mcu/nordic/include`
and one with `NRFX_STATIC_ASSERT` defined to nothing in 
`repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/templates`

If the templates include path is set before the first one in the gcc command the file compiles correctly (tested by manually running the failing gcc command). 

Alternatively, disabling `NRFX_GPIOTE_ENABLED` in `nrfx_config.h` in the bsp works around the issue too, if you're not relying on gpiote in your project.

**Pull request merged**
