### PR TITLE
hw/bus/drivers/spi_da1469x: Allow for 16-bit SPI transfers

### PR DESCRIPTION
**Pull request by wes3**
Changes allow for 16-bit DMA transfers for spi. Note that the current hal and other configuration code do not allow the spi to be configured for 16 bits. However, if this is configured outside the provided API this code will allow for the proper size transfer.

I do think that we should add 16-bit spi transfers to the HAL (for all hal spi) but this is a larger undertaking and I think this change would be independent (and the same) without doing that which is why I am putting in this PR without adding 16-bit spi for HAL

### CODE REVIEW

**Comment by kasjer** [comment]
While code looks OK when only PR title is considered what will happen if transfer length is less then `MIN_DMA_SIZE`. Then even though SPI is configured for 16 bits, interrupt handler will operate on bytes transmitting extra bytes (I suppose) and dropping every other received byte.

**Comment by wes3** [comment]
@kasjer That is a good point; I did not consider what would happen in the case DMA is not used. Let me review the code.

**Review by kasjer — APPROVED** [review]
Not tested but LGTM

**Comment by wes3** [comment]
I did some testing; here are some stats. I do a very large DMA transfer (programming an fpga and it succeeds) and then some other short ones. The "read" command consists of two bytes written and three read.

/* Send a read command */
013588 read_bytes: 3
013588 written_bytes: 104179
013589 dma_transferred_bytes: 104169

/* Send a read command */

014982 Read data: 00:00:03
compat> stat spi_da1469x_0

015598 read_bytes: 6
015598 written_bytes: 104181
015599 dma_transferred_bytes: 104169

**Pull request merged**
