### PR TITLE
Shell improvements before 1.1

### PR DESCRIPTION
**Pull request by michal-narajowski**
This patch introduces simplifications and improvements suggested by @cwanda.

Changes include:
* bringing back shell_evq_set
* directly using shell_register api in internal shell modules
* asserting when max number of modules exceeded 
* removing module name length limit
* adding prompt suffix option to syscfg
* some whitespace fixes

### CODE REVIEW

**Comment by cwanda** [comment]
Thanks, Michal for the updates. They look good and address my questions.

**Comment by sjanc** [comment]
Looks good to me.

**Comment by cwanda** [comment]
Please add conditional include #if MYNEWT_VAL(SHELL_OS_MODULE) around the shell_os.c code  #if MYNEWT_VAL(SHELL_PROMPT_MODULE) around the shell_prompt.c code. We have a tutorial that recommends users to disable SHELL features as a way to reduce application code size.

**Comment by michal-narajowski** [comment]
This is not necessary, because when there is no call to any function defined in a file then the file is not included in the final executable. You can check that with `newt size <target> -F`.

**Comment by cwanda** [comment]
Sorry about that. I weren't sure how the linker would handle the static data for the command and help structures etc and forgot about the newt size command to check.

**Pull request merged**
