### PR TITLE
Update lwip_base to LWIP 2.1.2

### PR DESCRIPTION
**Pull request by jeremywood**
Update the Mynewt `lwip_base` package from 2.0.3 to 2.1.2, the latest release version of LWIP.

Minimal changes to the 2.1.2 sources, all detailed in the updated `net/ip/lwip_base/MYNEWT`.

So far, I've tested on nRF52840 with PPPoS, no issues found. Would be great to have others test on other HW!

### CODE REVIEW

**Review by sjanc — APPROVED** [review]
Looks good to me.
Small nitpick: I'd probably squash first 3 commits but I'll not going to block merge if you think it is better as is now

**Comment by jeremywood** [comment]
@sjanc Thanks for the feedback—I agree, it's cleaner to combine those commits, which I've done.

**Comment by jeremywood** [comment]
@sjanc I'm not sure what happened with the CI errors, but I think this is ready to merge if you're happy with the commit history.

**Comment by utzig** [comment]
> @sjanc I'm not sure what happened with the CI errors, but I think this is ready to merge if you're happy with the commit history.

I think you can just disregard the CI for now, Travis needs to be migrated from .org to .com; I'll check how to proceed with that before it happens automatically.

**Comment by jeremywood** [comment]
What's the next step with this PR? I'm eager to get it merged so that I go back to tracking master instead of my fork.

**Comment by vrahane** [comment]
Next step is merging it @jeremywood.

**Pull request merged**
