### PR TITLE
kernel/os_msys: Improve finding mpool

### PR DESCRIPTION
**Pull request by rymanluk**
This PR does two things
1) When it search for mpool for given data size it pick mempool with a databuf_len closes to requested datasize. With this Mynewt tries to me smart and not used mempools with big block size for small data 

2) When user requests msys mbuf with data size 0, Mynewt assumes that data might be big, therefore it will assign mempool with biggest block size. It is done because if there would be msys_2 available with small block size for e.g. some headers as in https://github.com/apache/mynewt-nimble/pull/380, those small msys blocks would be consumed by  others e.g. OIC, where datasize 0 is requested for the reason that it is hard to estimate how big mbuf is needed.

### CODE REVIEW

**Comment by andrzej-kaczmarek** [comment]
it would work even better if we just sort pools by buffer size when registering them

**Comment by rymanluk** [comment]
thanks @wes3 , I saw the @andrzej-kaczmarek  comment too and like the idea. Will do it. 

btw, wondering why oic tests failes.. need to look into it.

**Comment by rymanluk** [comment]
improved according to @andrzej-kaczmarek  comment

**Comment by andrzej-kaczmarek** [comment]
so if pools re now sorted you do not need to loop over entire queue to find largest one - it will be the last one

**Comment by rymanluk** [comment]
@andrzej-kaczmarek  yeah, check the force pushed version two minutes before your comment :)   funny I was just writing this change while you were writing this comment.

**Pull request merged**
