### PR TITLE
Test travis integration

### PR DESCRIPTION
**Pull request by utzig**
WIP - DO NOT MERGE

### CODE REVIEW

**Comment by kaidokert** [comment]
I have a blinky building nightly on Travis here: https://travis-ci.org/kaidokert/mynewt-blinky/builds

Travis.yml here: https://github.com/kaidokert/mynewt-blinky/blob/master/.travis.yml

Maybe helpful ?

**Comment by jacobrosenthal** [comment]
Can we get a linter in here while were at it?

**Comment by utzig** [comment]
@jacobrosenthal What would you suggest?

**Comment by jacobrosenthal** [comment]
Im all ideas no solutions. 

My understanding is cpplint is completely opinionated and un-customizable?

Naive googling brought up a few projects that still seem sort of developed. Anyone have experience with any of them?

https://clang.llvm.org/docs/ClangFormatStyleOptions.html
https://github.com/kunaltyagi/nsiqcppstyle
https://sourceforge.net/p/astyle/code/HEAD/tree/
https://bitbucket.org/verateam/vera/branches/
https://github.com/JossWhittle/FlintPlusPlus/

**Comment by jacobrosenthal** [comment]
Something I just did for my private repo build server is reporting memory changes in PRs and Im really liking that.

My script looks like this
```
      - newt install -f
      - newt build split-shield
      - newt size split-shield # silly but current image doesnt have tee and i want to print to logs
      - newt size split-shield | grep -A1 $(printf "bss\t") | sed '1d;3d;4d' | cut -f1-5 > size_pr.txt
# do any testing you need here, then get your master and build that for comparison
      - git fetch
      - git checkout $(git show-ref -s --verify refs/remotes/origin/master)
      - newt clean all
      - newt install -f
      - newt build split-shield
      - newt size split-shield # silly but current image doesnt have tee and i want to print to logs
      - newt size split-shield | grep -A1 $(printf "bss\t") | sed '1d;3d;4d' | cut -f1-5 > size_master.txt
      - paste size_pr.txt size_master.txt | awk ' BEGIN { print "{\"body\":\"| text | data | bss | dec | \\\r\\\n | --- | --- | --- | --- | \\\r\\\n" } { print $1-$6" | "$2-$7" | "$3-$8" | "$4-$9"\\\r\\\n"} END   { print "\"}" }' > /drone/src/template.json
```

and reports that net change for app and loader back to github which looks like this

| text | data | bss | dec | 
 | --- | --- | --- | --- | 
12 | 0 | 1040 | 1052
12096 | 80 | 960 | 13136



 The only issue is its (obviously) entirely based on the a single target and doesnt tell you anything about non enabled settings, so its not exhaustive reporting, but tracking usage on bare minimum target would be really valuable for newt. I think back to me desperately trying to keep ble working on  the nrf51822's which Ive basically abandoned.

**Comment by jacobrosenthal** [comment]
Reporting back on linting. 

Astyle seems perfectly configurable for our uses but its a formatter and Im not super comfortable with that. Id rather get a report back on whats wrong. I spent some time trying to configure it as it has a --dry-run option but it just reports if it WOULD have changed a file, and doesnt return that in the error code at all. So we could fish out the result of how many files it would have changed in a PR, but we wouldnt have a log of what the user should actually do to appease it which I dont like. Maybe someone else here knows another way to use it? Otherwise Im going to look at the other tools

```
$ astyle --style=otbs --indent=spaces=4 --dry-run --lineend=linux -rvXQ --recursive repos/apache-mynewt-core/hw/drivers/drv2605/*.c
Artistic Style 3.1                                06/21/2018
------------------------------------------------------------
Directory  repos/apache-mynewt-core/hw/drivers/drv2605/*.c
------------------------------------------------------------
Formatted  src/drv2605.c
Formatted  src/drv2605_shell.c
------------------------------------------------------------
 2 formatted   0 unchanged   0.01 seconds   1,406 lines

$ echo $? 
0
$ 
```

**Comment by jacobrosenthal** [comment]
clang-format is a lot like astyle, in that its a formatter, but it DOES output its result to stdout by default and so I found an SO that offered this diff workaround (which we could probably implement for astyle if it came to it)

```
---
IndentCaseLabels: true
IndentWidth: 4
IncludeBlocks: Preserve
Language: Cpp
PointerAlignment: Right
UseTab: Never
BreakBeforeBraces: Stroustrup
---
```

```
clang-format -style=file repos/apache-mynewt-core/hw/drivers/drv2605/src/drv2605.c | diff repos/apache-mynewt-core/hw/drivers/drv2605/src/drv2605.c -
....
807,808c840
< int
< drv2605_config(struct drv2605 *drv2605, struct drv2605_cfg *cfg)
---
> int drv2605_config(struct drv2605 *drv2605, struct drv2605_cfg *cfg)
825c857
<     switch(cfg->op_mode) {
---
>     switch (cfg->op_mode) {
845,846c877
< int
< drv2605_load_rom(struct sensor_itf *itf, uint8_t* wav_ids, size_t len)
---
> int drv2605_load_rom(struct sensor_itf *itf, uint8_t *wav_ids, size_t len)
865,866c896
< int
< drv2605_trigger_rom(struct sensor_itf *itf)
---
> int drv2605_trigger_rom(struct sensor_itf *itf)
871,874c901,903
< // theres sadly no interrupt for knowing when long running roms are finished, youll need to block on this or set a callout
< // to poll for completion
< int
< drv2605_rom_busy(struct sensor_itf *itf, bool *status)
---
> // theres sadly no interrupt for knowing when long running roms are finished,
> // youll need to block on this or set a callout to poll for completion
> int drv2605_rom_busy(struct sensor_itf *itf, bool *status)
890,891c919
< int
< drv2605_load_rtp(struct sensor_itf *itf, uint8_t value)
---
> int drv2605_load_rtp(struct sensor_itf *itf, uint8_t value)
```
But its really aggressive out of the box. Its basically touching every line. I imagine I could eventually figure out all the rules i need to enable or disable. For better or worse this diff style doesnt tell you what you're doing wrong, just gives you the formatted output it wants.

**Comment by utzig** [comment]
@jacobrosenthal Sometime ago I added a config for uncrustify (https://github.com/uncrustify/uncrustify) which is available at the repo root. I quite like this tool because of its extreme configurability, but I still would have to relax some parameters to make it useful for general use (in particular what comes to mind is struct field formatting)...

**Comment by jacobrosenthal** [comment]
Looks good to me. Lets add that here!

**Comment by michal-narajowski** [comment]
@kaidokert Can you add Apache Licence 2.0 to your CI scripts so that I can use them in official Mynewt Travis CI repository?

**Comment by utzig** [comment]
This was superseeded by #1366

**Pull request closed without merging**
