### PR TITLE
WIP: SPI_4 and SPI_5 definitions

### PR DESCRIPTION
**Pull request by rafacouto**
Missing SPI definitions on STM32 common drivers. See issue #2385

### CODE REVIEW

**Comment by kasjer** [comment]
@rafacouto is this PR still in work in progress state?

**Review by kasjer — APPROVED** [review]
LGTM

**Comment by rafacouto** [comment]
> @rafacouto is this PR still in work in progress state?

I've tested that prebuilt macros are generated but I couldn't check if SPIs are operatives. Please, give me some more days to do a full test on board. I'll post the results in this thread.

**Comment by kasjer** [comment]
Hi @rafacouto changes were good, I tested it and since commit message was also nice I though that little WIP in PR name will not be a problem. Thanks for you contribution.

**Pull request merged**
