### PR TITLE
Pr bma253 20190708

### PR DESCRIPTION
**Pull request by bstbud**
add struct bma253_notif_cfg
add/use function bma253_find_notif_cfg_by_event in related notification functions

### CODE REVIEW

**Comment by vrahane** [comment]
@bstbud Thank you for adding this. Can you please also add orientation change notifications just like the ST sensors ?

**Comment by bstbud** [comment]
> 
> 
> @bstbud Thank you for adding this. Can you please also add orientation change notifications just like the ST sensors ?
Hi @vrahane  thanks for your feedback, we have got this orientation INT requirement, and will add it ASAP. since this is a new INT feature that we need to add and test, we plan to add it in next version 1.0.0.4 and create another Pull Request for orientation INT feature. About this bma253_notif_


> 
> 
> @bstbud Thank you for adding this. Can you please also add orientation change notifications just like the ST sensors ?



> 
> 
> @bstbud Thank you for adding this. Can you please also add orientation change notifications just like the ST sensors ?

Hi @vrahane  thanks for your feedback, we have got this orientation INT requirement, and will add it ASAP. since this is a new INT feature that we need to add and test, we plan to add it in next version 1.0.0.4 and will create another Pull Request for orientation INT feature. about adding and using struct bma253_notif_cfg, do you think it is ok?

**Comment by vrahane** [comment]
@bstbud it would be nice if you could add the orientation support to this PR itself, I don't think it is that much different.

**Comment by bstbud** [comment]
hi @vrahane  orientation change is already added.

**Comment by utzig** [comment]
@bstbud You need to rebase this on master to remove those merge commits and if you are fixing your own commits, like changing version, change tabs, this should be squashed into the original commit!

**Comment by bstbud** [comment]
Thanks for the comments, it is noted to the team.

B.R.

On Jul 9, 2019, at 07:50, Fabio Utzig <notifications@github.com<mailto:notifications@github.com>> wrote:


@bstbud<https://github.com/bstbud> You need to rebase this on master to remove those merge commits and if you are fixing your own commits, like changing version, change tabs, this should be squashed into the original commit!

**Comment by vrahane** [comment]
So, @bstbud opened a new PR https://github.com/apache/mynewt-core/pull/1912 with the above changes and some more modifications.

**Pull request closed without merging**
