### PR TITLE
nrf52: Add debugger override syscfg

### PR DESCRIPTION
**Pull request by vrahane**
- Add MCU_DEBUG_IGNORE_BKPT syscfg
- To be set if one wants to ignore debugger check

### CODE REVIEW

**Comment by vrahane** [comment]
@mkiiskila, @wes3 and @InternetofAwesome do you think this would be a good enough solution ?

**Comment by andrzej-kaczmarek** [comment]
what is the purpose of this setting?

**Comment by vrahane** [comment]
The MCU goes into a debug mode which it does not come out of and gets stuck on a breakpoint on doing a reset when a debugger is connected. There is no way to override this behavior. Hence, the setting just to skip this check and move on with a reset.

**Comment by sterlinghughes** [comment]
I don't think this is the right way to do this, as it changes the behaviour of hal_debugger_connected() to be wrong.  I'd rather apply to the setting to not issue asm(bkpt), then change the behavior of the function to be wrong.

**Comment by vrahane** [comment]
I spoke to @andrzej-kaczmarek in a DM, he was fine with adding MCU_DEBUG_IGNORE_DEBUGGER so that we can use it for other MCUs as well. I actually do not mind any implementation but with `asm("bkpt")` being called at various places, it seemed fine to use `hal_debugger_connected()`, so we have one central place for it.

**Comment by vrahane** [comment]
@sterlinghughes I made the changes and tried it out. Works fine. I'll update the PR.

**Comment by benmccrea** [comment]
@vrahane Hey, I'm late to the game here as this is merged, but I have a concern about this implementation. When the debugger is enabled the nRF52 will keep running off the HFXO, making for significantly higher current usage. Is it possible for it to kick itself out of debug mode, like `CoreDebug->DHCSR &= ~CoreDebug_DHCSR_C_DEBUGEN_Msk`? It seems like that would be preferable to just ignoring the asm("bkpt").

**Comment by andrzej-kaczmarek** [comment]
@benmccrea it's not possible - `C_DEBUGEN` bit is not writable by core

**Comment by vrahane** [comment]
@andrzej-kaczmarek We are not doing that, that bit gets reset on reboot. We just synced up on it. Also, you might be wrong about it not being writable, From the ARM reference manual:
`When C_DEBUGEN is set to 0, the processor ignores the values of all other bits in
this register.`

**Comment by andrzej-kaczmarek** [comment]
@vrahane `This bit can only be written by the DAP, it ignores writes from software.` (_ARMv7-M Architecture Reference Manual, C1.6.2_)

**Pull request merged**
