### PR TITLE
stats: Get rid of static qualifier for STATS_NAME_START

### PR DESCRIPTION
**Pull request by manish-sudo**

### CODE REVIEW

**Comment by kasjer** [comment]
Obviously change does something more beyond what is mention in the commit message.

It does not explain reasons behind the changed. Does it fix something? Is it some kind of improvement?

**Comment by manish-sudo** [comment]
@kasjer, here is the context:
https://github.com/apache/mynewt-core/issues/1968

Also, while digging in the code I found that some of the code is still using the old "apache-mynewt-core/mgmt/imgmgr" which now has been replaced by mcumgr "apache-mynewt-mcumgr/cmd/img_mgmt" which has been addressed as well.

**Comment by utzig** [comment]
@manish-sudo Pointing to an issue number here in the PR does not mean someone looking at git history will be able to understand why this change was made. You have to write it down in the commit, either copying from the body of the issue itself, or any other descriptive text that does not rely on external information.

**Comment by kasjer** [comment]
@manish-sudo package name fixes were somehow obvious (separate commit would be much batter though).
The other part (getting rid of static) is not clear, what was done was explained, why it was done, not so much.

**Comment by manish-sudo** [comment]
> @manish-sudo package name fixes were somehow obvious (separate commit would be much batter though).
> The other part (getting rid of static) is not clear, what was done was explained, why it was done, not so much.

Okay, let me close this PR then, I will break it down into two and also add some context in the commit. Thanks for your inputs!

**Comment by kasjer** [comment]
> > @manish-sudo package name fixes were somehow obvious (separate commit would be much batter though).
> > The other part (getting rid of static) is not clear, what was done was explained, why it was done, not so much.
> 
> Okay, let me close this PR then, I will break it down into two and also add some context in the commit. Thanks for your inputs!

Thanks for understanding and you contribution.

**Pull request closed without merging**
