### PR TITLE
SiFive Typo Fix

### PR DESCRIPTION
**Pull request by robertlipe**
Minor Typo fix.

### CODE REVIEW

**Comment by kasjer** [comment]
Hi @robertlipe here is what can be approved without fuzz.

Have just one pull request that changes both **hal_spi.c** and **fe310_hal.h** in one commit.
(no need to pull request #2560 then)
Don't rename file hal_spi.c.
make commit massage for your one commit like:
```git
mcu/fe310: Fix typo

Fix typo and duplicated function prototype.
```

Don't hesitate to use force push so your one commit is nice and don't need to be squashed on merge.
If something is not clear in my comment we can work it out.

best regards
Jerzy

**Comment by robertlipe** [comment]
Thanx, Jerzy. I'd forgotten what a disaster the "edit file" web interface makes of a multiple file change. There was no renaming. I don't know what kind of drugs git is on. I just checked it out locally and fixed it in my tree. There isn't a "hello, blinky" for RISC-V targets, so I'm still working out how to actually build it.

I'll drop these in favor of https://github.com/apache/mynewt-core/pull/2565

Thanx for the gentle nudge.

**Comment by kasjer** [comment]
Hi @robertlipe, here is what you need to do to run blinky on hifive1 board:

create target for bootloader:
```sh
newt target create riscv-boot
newt target set riscv-boot app=@mcuboot/boot/mynewt
newt target set riscv-boot bsp=@apache-mynewt-core/hw/bsp/hifive1
newt target set riscv-boot build_profile=optimized
```
create target for blinky application
```sh
newt target create riscv-blink
newt target set riscv-blinky bsp=@apache-mynewt-core/hw/bsp/hifive1
newt target set riscv-blinky app=apps/blinky
newt target set riscv-blinky build_profile=debug
```
build bootloader (bin) and application (img)
```sh
newt build riscv-boot
newt create-image riscv-blinky timestamp
```
now load bootloader and application
```sh
newt load riscv-boot
newt load riscv-blinky
```

This all assumes that you have **openocd** with riscv support installed and that
your compiler is **riscv64-unknown-elf-gcc** which was what originally used from freedom sdk.
Now it maybe more common to use **riscv-none-embed**, if this is the case for start you can
update **compiler/riscv64/compiler.yml** to use prefix that you have compiler for.

best regards
Jerzy

**Comment by robertlipe** [comment]
Thanx for the help. I'll take advantage of your generosity and just ask for
help, because this isn't that different than what I came up with and it's
not working. In fact, if I try any of the other targets, exercising the
configuration machinery and *expecting* a failure at compile time, it fails
pretty much the same way.  Though 'git status' is happy with my
mynewt-core, I'm wondering if my installation is borked.

***@***.***Mac7 mynewt-core % cat go
yes | newt target delete riscv-boot
yes | newt target delete riscv-blinky


newt target create riscv-boot
newt target set riscv-boot ***@***.***/boot/mynewt
newt target set riscv-boot ***@***.***/hw/bsp/hifive1
newt target set riscv-boot build_profile=optimized

# create target for blinky application
newt target create riscv-blinky
newt target set riscv-blinky ***@***.***/hw/bsp/hifive1
newt target set riscv-blinky app=apps/blinky
newt target set riscv-blinky build_profile=debug

# visually confirm success of above
newt target show

# build bootloader (bin) and application (img)
newt build riscv-boot
newt build riscv-blinky

newt create-image riscv-blinky timestamp
***@***.***Mac7 mynewt-core % ./go
Target directory /Users/robertlipe/tmp/mynewt-core/targets/riscv-boot
contains some extra content; delete anyway? (y/N): Target
targets/riscv-boot successfully deleted.
Target directory /Users/robertlipe/tmp/mynewt-core/targets/riscv-blinky
contains some extra content; delete anyway? (y/N): Target
targets/riscv-blinky successfully deleted.
Target targets/riscv-boot successfully created
Target targets/riscv-boot successfully set target.app to
@mcuboot/boot/mynewt
Target targets/riscv-boot successfully set target.bsp to
@apache-mynewt-core/hw/bsp/hifive1
Target targets/riscv-boot successfully set target.build_profile to optimized
Target targets/riscv-blinky successfully created
Target targets/riscv-blinky successfully set target.bsp to
@apache-mynewt-core/hw/bsp/hifive1
Target targets/riscv-blinky successfully set target.app to apps/blinky
Target targets/riscv-blinky successfully set target.build_profile to debug
targets/riscv-blinky
    app=apps/blinky
    ***@***.***/hw/bsp/hifive1
    build_profile=debug
targets/riscv-boot
    ***@***.***/boot/mynewt
    ***@***.***/hw/bsp/hifive1
    build_profile=optimized
Building target targets/riscv-boot
Error: Could not resolve app package: @mcuboot/boot/mynewt
Building target targets/riscv-blinky
Error: Could not resolve app package: apps/blinky
Error: Could not resolve app package: apps/blinky

If mcuboot should resolve to the top of the tree like @apache-mynewt-core
does and find that /boot directory, there will be sadness as there is no
mynewt:
 % ls boot
split split_app stub
As for not resolving the app package, there isn't a blinky in my apps dir,
but there isn't one viewing the repo on github.

I once saw compliation action, but even after the target deletion above
I've not seen it compile anything since.


As for FTDI board vs. JTAG and such, once I can get a linked binary, I'll
be in good shape.  The compiler name is perfect; it's the one supplied by
the RISC-V comopiler team in the binary kits, so it's already in the $PATH
of most RISC-V devs. It's easier to use the risc64...gcc with the flags to
emit 32-bit code than to build a 32-bit only version of the GNU chain.
Actually, I'm tearing into this with the intent of teaching mynewt  about
more RISC-V BSPs, splitting the F310 into rv32 and rv64 generic plua system
modules and then fleshing out the eval boards that I have here.

Thanx!

**Comment by kasjer** [comment]
@robertlipe 
Lets try this:
```sh
newt new myproj
cd myproj
newt upgrade
```
then you should have all the missing pieces and previous commands should work.
this `newt new` sets up **project.yml** (and maybe something else) that is really needed.
Having mynewt-core is not enough I guess.
Let me know it it helped.

best regards
Jerzy

**Comment by robertlipe** [comment]
That's close enough I can work with that. I at least now get compiling
action (yay!) and two .elf's at the end. So I think we're pretty close to
the finish line.

Is this using the mynewt-core that's in the parent directory (newt target
show kind of hides the expansion of @apache-mynewt-core) or is it using one
squirreled away by the system during the original install of Newt, in my
case from brew install?)  Just injecting an error
into  repos/apache-mynewt-core/libc/baselibc/src/malloc.c makes me think
it's making another copy that's not directly managed by git (git diff
doesn't show my modified malloc), even though I can see it did a download
from github).  That's still not very clear. If I compare it to having a
checked out version of gcc and we run "mkdir blah; cd blah; newt new
myprot", does it use the GCC in the parent ($(WHATEVER)/myproj/.. or does
it use the GCC in $PATH? The files aren't symlinks; they're a copy from
somewhere and it doesn't seem to be the one
from ../libc/baselibc/src/malloc.c.

create-image is unhappy, but I see now that it wasn't in your notes at all.
Must have been something I picked up elsewhere on the web.

 % newt create-image riscv-blinky timestamp
panic: unexpected error type: *exec.Error

goroutine 1 [running]:
mynewt.apache.org/newt/newt/cli.NewtUsage(0x0, 0x44767e0, 0xc0003d2060)
/tmp/mynewt.I6rLnNiTvo/src/mynewt.apache.org/newt/newt/cli/util.go:54 +0x3cd
mynewt.apache.org/newt/newt/cli.createImageRunCmd(0xc000170280,
0xc00005c4a0, 0x2, 0x2)
/tmp/mynewt.I6rLnNiTvo/src/mynewt.apache.org/newt/newt/cli/image_cmds.go:146
+0x33f
github.com/spf13/cobra.(*Command).execute(0xc000170280, 0xc00005c400, 0x2,
0x2, 0xc000170280, 0xc00005c400)
/private/tmp/mynewt-newt-20210413-96689-1rzcubs/.brew_home/go/pkg/mod/
***@***.***/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc00012aa00, 0x4417d73, 0xc,
0x3)
/private/tmp/mynewt-newt-20210413-96689-1rzcubs/.brew_home/go/pkg/mod/
***@***.***/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
/private/tmp/mynewt-newt-20210413-96689-1rzcubs/.brew_home/go/pkg/mod/
***@***.***/command.go:864
main.main()
/tmp/mynewt.I6rLnNiTvo/src/mynewt.apache.org/newt/newt/newt.go:183 +0x1a5

My guess is that it's some kind of a FNF error, but that Go is taking from
Python and giving us a stupid stack trace from files that are deleted on
command instead of an actual error message like *what* file was not
found... (Personal rant...)

I'll have to think how I feel about a split bootloader for some of my
really tiny targets with as little as 8K of RAM. A bootloader that's larger
than the app (I get that blinky being small is the point) is not great.
 % riscv64-unknown-elf-size
.***@***.***/boot/mynewt/mynewt.elf
./bin/targets/riscv-blinky/app/apps/blinky/blinky.elf
   text   data    bss    dec    hex filename
  15288     12   7000  22300   571c
.***@***.***/boot/mynewt/mynewt.elf
  13690     28   9236  22954   59aa
./bin/targets/riscv-blinky/app/apps/blinky/blinky.elf
I also know this was written for a completely different board that may not
share these constraints.

This has been a superhelpful fast-forward. I appreciate it. Hopefully I'll
make friends with mynewt (it seems to get a lot of my personal peeves
right) and we'll have a productive relationship. Thanx!
RJL

P.S. Yes, one of my first steps will be writing a 'hello risc-v" that
distills our learnings above.

**Comment by robertlipe** [comment]
Answering myself:

newt target create actually does four complete git checkouts in that
project:

./repos/apache-mynewt-mcumgr/.git
./repos/apache-mynewt-core/.git
./repos/apache-mynewt-nimble/.git
./repos/mcuboot/.git

and those checkouts are shared by any actual target in that directory. This
is why my 'git diff' at the top level showed nothing - it's not a repo.
Stepping into any of those directories inside repos is a real git
repository that appears to be independent of the parent totally.


./repos/apache-mynewt-mcumgr/.git
./repos/apache-mynewt-core/.git
./repos/apache-mynewt-nimble/.git
./repos/mcuboot/.git

 % git diff
diff --git a/libc/baselibc/src/malloc.c b/libc/baselibc/src/malloc.c
index 2bf45515d..17e4e458e 100644
--- a/libc/baselibc/src/malloc.c
+++ b/libc/baselibc/src/malloc.c
@@ -1,4 +1,4 @@
-/*

*+bigbooger/**  * malloc.c
  *
  * Very simple linked-list based malloc()/free().
***@***.***Mac7 repos % cd *core
***@***.***Mac7 apache-mynewt-core % git diff
diff --git a/libc/baselibc/src/malloc.c b/libc/baselibc/src/malloc.c
index 2bf45515d..39e024205 100644
--- a/libc/baselibc/src/malloc.c
+++ b/libc/baselibc/src/malloc.c
@@ -1,3 +1,4 @@

*+booger* /*
  * malloc.c
  *


Thus, a 'newt target create' isn't a particularly lightweght operation,
checking out about a half gig. It's pretty awesome that we can accidentally
check out a half gig from SCM and not even know it. This means any targets
created in that directory will share those above four repose (mcumgr, core,
nimble, mcuboot) but if you create in a completely different directory,
you'll get another copy. This looks pretty awesome for A/B testing if
you're working on the tools themselve.

The lightbulbs are going off.  I'll ocntinue to dig deeper into this. Thanx!

**Comment by kasjer** [comment]
```newt target create``` creates just 3 files
```newt upgrade``` downloads repositories

Users usually create project with ```newt newt```, this will have folder repos with several gits.
Then they create git for their projects versioning **project.yml** along with *apps* and other folders.
Sample blinky application that is created during *newt newt* is not put in any repository at the start.

*timestamp* parameter for create-image can be changed with something like 1.0.0.0. I was no aware of any problems it may create.
I don't know if this is mac version issue or not.

It is possible to have project that does not use bootloader and then after `newt build <target>` there is no need to execute `newt create-image <target>` just `newt load <target>`. In that case linker script for boot loader should be selected.

**Pull request closed without merging**
