### PR TITLE
hw/drivers/lps33thw:Added support to FIFO

### PR DESCRIPTION
**Pull request by mariotesi**
hw/drivers/lps33thw:Remove duplicated bitmask
    
        The F_FTH bitmask already defined and
        duplicated in CTRL_REG3

Signed-off-by: tesimari <mario.tesi@st.com>

### CODE REVIEW

**Comment by vrahane** [comment]
Thanks for doing this Mario, however, I think the changes should be put in the earlier PR itself. You do not need a separate PR for this.

**Comment by mariotesi** [comment]
@ vrahane the PR is related to lps33thw driver already merged in master, I rewrote the  message replacing lps33thw in place of wrong device lps33wh, sorry for mistake (those devices have almost the same name and I got confused)

**Comment by vrahane** [comment]
@mariotesi So, you are actually fixing a bug, can you please update the comment above ?

**Comment by mariotesi** [comment]
ok, done

**Pull request merged**
