### PR TITLE
hw/mcu/dialog: Acquire PD_SYS for DMA

### PR DESCRIPTION
**Pull request by andrzej-kaczmarek**
DMA controller resides in PD_SYS domain so we cannot turn off that
domain if any DMA channes is acquired. That basically means on 1st
acquired DMA channel we need to also acquire PD which we can release
after last DMA channel is released. Note that acquiring PD_SYS means
M33 cannot be powered down in deep sleep.

### CODE REVIEW

**Comment by andrzej-kaczmarek** [comment]
@JustineKH ^^

**Comment by agross-korg** [comment]
I really don't like the overall design of the power management.  This patch fixes the issue of instability when we go to deep sleep while the DMA is active.  This patch also introduces increased power usage if we happen to go to deep sleep while the DMA is active.

**Comment by agross-korg** [comment]
I'm saying that once we fix this we have more work to do to make this power efficient.

**Review by kasjer — APPROVED** [review]

**Review by agross-korg — APPROVED** [review]

**Review by nkaje — APPROVED** [review]

**Review by wes3 — APPROVED** [review]
This is odd. I thought I added a review but it appears not. I took the code and did some rudimentary testing.

**Pull request merged**
