### PR TITLE
mbedtls; add a routine to add AAD data incrementally.

### PR DESCRIPTION
**Pull request by mkiiskila**

### CODE REVIEW

**Comment by sterlinghughes** [comment]
Is this a core mbedtls function or added by us?  If added by us, we should find a way to not have it in core distro (or upstream fix), so that we can maintain / upgrade mbedtls more easily.

**Comment by mkiiskila** [comment]
There's a PR against upstream mbedtls now. Includes this change as well as the previously added GCM related routine. See https://github.com/ARMmbed/mbedtls/pull/2583

**Comment by utzig** [comment]
Btw, the CI did not pass for upstream, I'm not sure they will review it in this state.

**Comment by utzig** [comment]
The reason the CI failed it that `mbedtls_gcm_setkey_noalloc` has an argument named `cipher_info` and in the doxygen header you wrote `\param cipher    The 128-bit block cipher to use.`. Both names should match, and fixing this should enable it to pass...

**Pull request merged**
