### PR TITLE
bsp: allow override of i2c, spis and spim pins

### PR DESCRIPTION
**Pull request by jacobrosenthal**
Uart pins are allowed to be overridden but not i2c and spis/spim. If this is wanted Ill do the other boards as well

### CODE REVIEW

**Comment by wes3** [comment]
Changes look good to me.

**Comment by jacobrosenthal** [comment]
Hopefully I havent broken anything. But as a result Ive left nrf51-blenano and calliope_mini unchanged as they had existing definitions for i2c freq and I didnt want to break them (yet)

Also of note, we have another inconsistency in that many nrf51 boards seem to create a spi_0_master and spi_1_slave but nrf52 boards seem to create an spi_0_slave. We could attempt to clean this up now, but again that would break existing bsps...

**Comment by wes3** [comment]
I guess I should have commented on this here. The nrf51 does not have a spi0 slave; that is the reason.

**Comment by wes3** [comment]
@jacobrosenthal After seeing all the files that have changed (my original "looks good" was only after seeing changes to one bsp) I am thinking that it would probably have been best to put the MYNEWT_VAL definitions for the pins in the MCU as opposed to each BSP. I wonder what others think? Seems to make sense to me as it will mean we will have to duplicate less stuff in each bsp syscfg.

**Pull request merged**
