### PR TITLE
Add MCU_PRE_BKPT_CB() syscfg

### PR DESCRIPTION
**Pull request by vrahane**
- It should get called before asm("bkpt") gets called

### CODE REVIEW

**Comment by andrzej-kaczmarek** [comment]
syscfg is defined in nrf package, but also used in `arch/cortex_m4` - I don't think this is a good idea.

also I agree with @ccollins476ad that syscfg should not be named after `bkpt` since it has nothing to do with `bktp` instruction in general. a better names imo would be e.g. `MCU_PRE_RESET_CALLBACK` and `OS_ASSERT_CALLBACK`.

and my last concern is that this specifies name of a function so basically this injects piece of source code which I do not really like - a better idea would be to have a predefined callback which application should define if this option is enabled.

**Comment by vrahane** [comment]
I just merged it and your comment popped up. Will address your comments soon.

**Comment by ccollins476ad** [comment]
@andrzej-kaczmarek, if I understand, you are suggesting that the application configure a callback at runtime.  I agree that injecting code via syscfg is a bit messy, but I think it is appropriate for this case.  I believe this PR implements a "safety feature" - the specified code must run every time the device resets.  If the reset occurs before the application can configure the callback, then that is not good.

**Comment by andrzej-kaczmarek** [comment]
@ccollins476ad by "predefined callback" I meant function declaration which is called here and should be implemented by application if this option is enabled. and you have a good point why we should not use an actual callback here instead.

**Comment by ccollins476ad** [comment]
@andrzej-kaczmarek makes sense.

**Pull request merged**
