### PR TITLE
kernel/os: Make sure correct stack aligment 

### PR DESCRIPTION
**Pull request by rymanluk**
This PR has been done after testing of  #882

### CODE REVIEW

**Comment by sterlinghughes** [comment]
I agree - I don't know who this DENIFE is.  :-) Why is attribute(aligned) required, shouldn't OS_STACK_ALIGN and the size of os_stack_t give you that?

**Comment by andrzej-kaczmarek** [comment]
@sterlinghughes `OS_STACK_ALIGN` will align size to 8 bytes, but since `os_stack_t` is `uint32_t` array will be aligned to 4 bytes only. We could change `os_stack_t` to `uint64_t` but I don't think this makes sense since word size is still 32-bits, just the alignment should be different.

**Comment by sterlinghughes** [comment]
makes sense.  @rymanluk can you fix typo, and then we can merge?

**Comment by sterlinghughes** [comment]
btw, i can't believe this is the only place we define OS stacks.  we should definitely highlight this for users, as this will affect anybody who declares a task and uses floating point.

**Comment by ccollins476ad** [comment]
Good catch.  It looks like there is another related issue.  `os_malloc()` doesn't always return 8-byte aligned blocks.  Some apps (e.g., slinky) malloc task stacks.  If the allocated stack is only 4-byte aligned, then we'll have this same issue.  This happened to me when I was testing the floating point printf PR with the slinky app.

Just for completeness (n1570, 7.22.3 (Memory management functions)):
> The pointer returned if the allocation succeeds is suitably aligned so that it may be assigned to a pointer to any type of object with a fundamental alignment requirement

I will file a separate PR for this.

**Comment by rymanluk** [comment]
fixed that typo - ehh. Please review.
I planned to update documentation anyway, will do it

**Pull request merged**
