### PR TITLE
Travis testing - RAT report

### PR DESCRIPTION
**Pull request by utzig**
Add RAT reporting to build matrix
    
@michal-narajowski This will need rebase after mynewt-travis-ci changes are merged.

### CODE REVIEW

**Comment by michal-narajowski** [comment]
### 3 Unknown Licenses

<details><summary>Details</summary>
<p>

<pre>

Summary
-------
Generated at: 2018-10-29T16:44:58+00:00

Notes: 0
Binaries: 0
Archives: 0
Standards: 3

Apache Licensed: 0
Generated Documents: 0

JavaDocs are generated, thus a license header is optional.
Generated files do not require license headers.

3 Unknown Licenses


------


Files with unapproved licenses:

  hw/mcu/fake/a.c
  hw/mcu/fake/b.c
  hw/mcu/fake/c.c


------
Files with Apache License headers will be marked AL
Binary files (which do not require any license headers) will be marked B
Compressed archives will be marked A
Notices, licenses etc. will be marked N
!????? <a href="https://github.com/apache/mynewt-core/blob/e7a81edb08d1342982936ccd6c8bc5a4d9fdcae6/hw/mcu/fake/a.c">hw/mcu/fake/a.c</a>
!????? <a href="https://github.com/apache/mynewt-core/blob/e7a81edb08d1342982936ccd6c8bc5a4d9fdcae6/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>
!????? <a href="https://github.com/apache/mynewt-core/blob/e7a81edb08d1342982936ccd6c8bc5a4d9fdcae6/hw/mcu/fake/c.c">hw/mcu/fake/c.c</a>
</pre>

</p>
</details>

**Comment by michal-narajowski** [comment]
### 3 Unknown Licenses

<details><summary>Details</summary>
<p>

<pre>

Summary
-------
Generated at: 2018-10-29T17:04:00+00:00

Notes: 0
Binaries: 0
Archives: 0
Standards: 3

Apache Licensed: 0
Generated Documents: 0

JavaDocs are generated, thus a license header is optional.
Generated files do not require license headers.

3 Unknown Licenses


------


Files with unapproved licenses:

  hw/mcu/fake/a.c
  hw/mcu/fake/b.c
  hw/mcu/fake/c.c


------
Files with Apache License headers will be marked AL
Binary files (which do not require any license headers) will be marked B
Compressed archives will be marked A
Notices, licenses etc. will be marked N
!????? <a href="https://github.com/apache/mynewt-core/blob/e7a81edb08d1342982936ccd6c8bc5a4d9fdcae6/hw/mcu/fake/a.c">hw/mcu/fake/a.c</a>
!????? <a href="https://github.com/apache/mynewt-core/blob/e7a81edb08d1342982936ccd6c8bc5a4d9fdcae6/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>
!????? <a href="https://github.com/apache/mynewt-core/blob/e7a81edb08d1342982936ccd6c8bc5a4d9fdcae6/hw/mcu/fake/c.c">hw/mcu/fake/c.c</a>
</pre>

</p>
</details>

**Comment by utzig** [comment]
@michal-narajowski Please stop commenting on my PR! :-)

**Comment by utzig** [comment]
### 3 Unknown Licenses

<details><summary>Details</summary>
<p>

<pre>

Summary
-------
Generated at: 2018-10-29T17:08:42+00:00

Notes: 0
Binaries: 0
Archives: 0
Standards: 3

Apache Licensed: 0
Generated Documents: 0

JavaDocs are generated, thus a license header is optional.
Generated files do not require license headers.

3 Unknown Licenses


------


Files with unapproved licenses:

  hw/mcu/fake/a.c
  hw/mcu/fake/b.c
  hw/mcu/fake/c.c


------
Files with Apache License headers will be marked AL
Binary files (which do not require any license headers) will be marked B
Compressed archives will be marked A
Notices, licenses etc. will be marked N
!????? <a href="https://github.com/apache/mynewt-core/blob/b8cc4eab71b5263ccdf9f5a027e4cdf289df784b/hw/mcu/fake/a.c">hw/mcu/fake/a.c</a>
!????? <a href="https://github.com/apache/mynewt-core/blob/b8cc4eab71b5263ccdf9f5a027e4cdf289df784b/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>
!????? <a href="https://github.com/apache/mynewt-core/blob/b8cc4eab71b5263ccdf9f5a027e4cdf289df784b/hw/mcu/fake/c.c">hw/mcu/fake/c.c</a>
</pre>

</p>
</details>

**Comment by utzig** [comment]
## RAT Report (2018-10-30 18:17:37)

## New files with unknown licenses

* <a href="hw/mcu/fake/b.c">https://github.com/apache/mynewt-core/blob/9b116e90186a6b1985e50d66ae60937c7c434c9c/hw/mcu/fake/b.c</a>


## New files

* MIT    <a href="https://github.com/apache/mynewt-core/blob/9b116e90186a6b1985e50d66ae60937c7c434c9c/hw/mcu/fake/a.c">hw/mcu/fake/a.c</a>

* ?????  <a href="https://github.com/apache/mynewt-core/blob/9b116e90186a6b1985e50d66ae60937c7c434c9c/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>

* GPL3   <a href="https://github.com/apache/mynewt-core/blob/9b116e90186a6b1985e50d66ae60937c7c434c9c/hw/mcu/fake/c.c">hw/mcu/fake/c.c</a>

**Comment by utzig** [comment]
## RAT Report (2018-10-30 18:48:45)

## New files with unknown licenses

* <a href="https://github.com/apache/mynewt-core/blob/9b289de2dfcb4ede630ccaa8e7a9696fb8981a41/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>

## New files

* MIT    <a href="https://github.com/apache/mynewt-core/blob/9b289de2dfcb4ede630ccaa8e7a9696fb8981a41/hw/mcu/fake/a.c">hw/mcu/fake/a.c</a>
* ?????  <a href="https://github.com/apache/mynewt-core/blob/9b289de2dfcb4ede630ccaa8e7a9696fb8981a41/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>
* GPL3   <a href="https://github.com/apache/mynewt-core/blob/9b289de2dfcb4ede630ccaa8e7a9696fb8981a41/hw/mcu/fake/c.c">hw/mcu/fake/c.c</a>

**Comment by utzig** [comment]
## RAT Report (2018-10-30 19:54:33)

## New files with unknown licenses

* <a href="https://github.com/apache/mynewt-core/blob/3449096/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>

## New files

* MIT    <a href="https://github.com/apache/mynewt-core/blob/3449096/hw/mcu/fake/a.c">hw/mcu/fake/a.c</a>
* ?????  <a href="https://github.com/apache/mynewt-core/blob/3449096/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>
* GPL3   <a href="https://github.com/apache/mynewt-core/blob/3449096/hw/mcu/fake/c.c">hw/mcu/fake/c.c</a>

**Comment by utzig** [comment]
## RAT Report (2018-10-30 19:58:24)

## New files with unknown licenses

* <a href="https://github.com/apache/mynewt-core/blob/3449096/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>

## New files

* MIT    <a href="https://github.com/apache/mynewt-core/blob/3449096/hw/mcu/fake/a.c">hw/mcu/fake/a.c</a>
* ?????  <a href="https://github.com/apache/mynewt-core/blob/3449096/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>
* B      <a href="https://github.com/apache/mynewt-core/blob/1765c5a/hw/mcu/fake/blinky.elf.bin">hw/mcu/fake/blinky.elf.bin</a>
* GPL3   <a href="https://github.com/apache/mynewt-core/blob/3449096/hw/mcu/fake/c.c">hw/mcu/fake/c.c</a>
* AL     <a href="https://github.com/apache/mynewt-core/blob/1765c5a/hw/mcu/fake/d.c">hw/mcu/fake/d.c</a>
* A      <a href="https://github.com/apache/mynewt-core/blob/1765c5a/hw/mcu/fake/somebin.tar.gz">hw/mcu/fake/somebin.tar.gz</a>

**Comment by utzig** [comment]
## RAT Report (2018-10-30 20:21:10)

## New files with unknown licenses

* <a href="https://github.com/apache/mynewt-core/blob/3449096/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>

## New files

* MIT    <a href="https://github.com/apache/mynewt-core/blob/3449096/hw/mcu/fake/a.c">hw/mcu/fake/a.c</a>
* ?????  <a href="https://github.com/apache/mynewt-core/blob/3449096/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>
* B      <a href="https://github.com/apache/mynewt-core/blob/1765c5a/hw/mcu/fake/blinky.elf.bin">hw/mcu/fake/blinky.elf.bin</a>
* GPL3   <a href="https://github.com/apache/mynewt-core/blob/3449096/hw/mcu/fake/c.c">hw/mcu/fake/c.c</a>
* AL     <a href="https://github.com/apache/mynewt-core/blob/1765c5a/hw/mcu/fake/d.c">hw/mcu/fake/d.c</a>
* A      <a href="https://github.com/apache/mynewt-core/blob/1765c5a/hw/mcu/fake/somebin.tar.gz">hw/mcu/fake/somebin.tar.gz</a>

**Comment by utzig** [comment]
## RAT Report (2018-10-30 20:44:20)

## New files with unknown licenses

* <a href="https://github.com/apache/mynewt-core/blob/3449096dd4409bbd01146bbc0b644b3a47e95c02/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>

<details>
  <summary>Detailed analysis</summary>
## New files

| License | File |
|---------|------|
| MIT    | <a href="https://github.com/apache/mynewt-core/blob/3449096dd4409bbd01146bbc0b644b3a47e95c02/hw/mcu/fake/a.c">hw/mcu/fake/a.c</a> |
| ?????  | <a href="https://github.com/apache/mynewt-core/blob/3449096dd4409bbd01146bbc0b644b3a47e95c02/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a> |
| B      | <a href="https://github.com/apache/mynewt-core/blob/1765c5a641588470dbaf3d765e65103437df633f/hw/mcu/fake/blinky.elf.bin">hw/mcu/fake/blinky.elf.bin</a> |
| GPL3   | <a href="https://github.com/apache/mynewt-core/blob/3449096dd4409bbd01146bbc0b644b3a47e95c02/hw/mcu/fake/c.c">hw/mcu/fake/c.c</a> |
| AL     | <a href="https://github.com/apache/mynewt-core/blob/1765c5a641588470dbaf3d765e65103437df633f/hw/mcu/fake/d.c">hw/mcu/fake/d.c</a> |
| A      | <a href="https://github.com/apache/mynewt-core/blob/1765c5a641588470dbaf3d765e65103437df633f/hw/mcu/fake/somebin.tar.gz">hw/mcu/fake/somebin.tar.gz</a> |
</details>

**Comment by utzig** [comment]
## RAT Report (2018-10-30 20:48:19)

## New files with unknown licenses

* <a href="https://github.com/apache/mynewt-core/blob/3449096dd4409bbd01146bbc0b644b3a47e95c02/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>

<details>
  <summary>Detailed analysis</summary>

## New files in this PR

| License | File |
|---------|------|
| MIT    | <a href="https://github.com/apache/mynewt-core/blob/3449096dd4409bbd01146bbc0b644b3a47e95c02/hw/mcu/fake/a.c">hw/mcu/fake/a.c</a> |
| ?????  | <a href="https://github.com/apache/mynewt-core/blob/3449096dd4409bbd01146bbc0b644b3a47e95c02/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a> |
| B      | <a href="https://github.com/apache/mynewt-core/blob/1765c5a641588470dbaf3d765e65103437df633f/hw/mcu/fake/blinky.elf.bin">hw/mcu/fake/blinky.elf.bin</a> |
| GPL3   | <a href="https://github.com/apache/mynewt-core/blob/3449096dd4409bbd01146bbc0b644b3a47e95c02/hw/mcu/fake/c.c">hw/mcu/fake/c.c</a> |
| AL     | <a href="https://github.com/apache/mynewt-core/blob/1765c5a641588470dbaf3d765e65103437df633f/hw/mcu/fake/d.c">hw/mcu/fake/d.c</a> |
| A      | <a href="https://github.com/apache/mynewt-core/blob/1765c5a641588470dbaf3d765e65103437df633f/hw/mcu/fake/somebin.tar.gz">hw/mcu/fake/somebin.tar.gz</a> |
</details>

**Comment by utzig** [comment]
## RAT Report (2018-10-30 21:29:07)

## New files with unknown licenses

* <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>

<details>
  <summary>Detailed analysis</summary>

## New files in this PR

| License | File |
|---------|------|
| MIT    | <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/a.c">hw/mcu/fake/a.c</a> |
| ?????  | <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a> |
| B      | <a href="https://github.com/apache/mynewt-core/blob/8552b65005101b9d318e3a9b371924807a1bb6e2/hw/mcu/fake/blinky.elf.bin">hw/mcu/fake/blinky.elf.bin</a> |
| GPL3   | <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/c.c">hw/mcu/fake/c.c</a> |
| AL     | <a href="https://github.com/apache/mynewt-core/blob/8552b65005101b9d318e3a9b371924807a1bb6e2/hw/mcu/fake/d.c">hw/mcu/fake/d.c</a> |
| A      | <a href="https://github.com/apache/mynewt-core/blob/8552b65005101b9d318e3a9b371924807a1bb6e2/hw/mcu/fake/somebin.tar.gz">hw/mcu/fake/somebin.tar.gz</a> |
</details>

**Comment by utzig** [comment]
## RAT Report (2018-10-31 10:10:32)

## New files with unknown licenses

* <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>

<details>
  <summary>Detailed analysis</summary>

## New files in this PR

| License | File |
|---------|------|
| MIT    | <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/a.c">hw/mcu/fake/a.c</a> |
| ?????  | <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a> |
| B      | <a href="https://github.com/apache/mynewt-core/blob/8552b65005101b9d318e3a9b371924807a1bb6e2/hw/mcu/fake/blinky.elf.bin">hw/mcu/fake/blinky.elf.bin</a> |
| GPL3   | <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/c.c">hw/mcu/fake/c.c</a> |
| AL     | <a href="https://github.com/apache/mynewt-core/blob/8552b65005101b9d318e3a9b371924807a1bb6e2/hw/mcu/fake/d.c">hw/mcu/fake/d.c</a> |
| A      | <a href="https://github.com/apache/mynewt-core/blob/8552b65005101b9d318e3a9b371924807a1bb6e2/hw/mcu/fake/somebin.tar.gz">hw/mcu/fake/somebin.tar.gz</a> |
</details>

**Comment by utzig** [comment]
## RAT Report (2018-10-31 13:55:50)

## New files with unknown licenses

* <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>

<details>
  <summary>Detailed analysis</summary>

## New files in this PR

| License | File |
|---------|------|
| MIT    | <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/a.c">hw/mcu/fake/a.c</a> |
| ?????  | <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a> |
| B      | <a href="https://github.com/apache/mynewt-core/blob/8552b65005101b9d318e3a9b371924807a1bb6e2/hw/mcu/fake/blinky.elf.bin">hw/mcu/fake/blinky.elf.bin</a> |
| GPL3   | <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/c.c">hw/mcu/fake/c.c</a> |
| AL     | <a href="https://github.com/apache/mynewt-core/blob/8552b65005101b9d318e3a9b371924807a1bb6e2/hw/mcu/fake/d.c">hw/mcu/fake/d.c</a> |
| A      | <a href="https://github.com/apache/mynewt-core/blob/8552b65005101b9d318e3a9b371924807a1bb6e2/hw/mcu/fake/somebin.tar.gz">hw/mcu/fake/somebin.tar.gz</a> |
</details>

**Comment by utzig** [comment]
## RAT Report (2018-10-31 14:07:36)

## New files with unknown licenses

* <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>

<details>
  <summary>Detailed analysis</summary>

## New files in this PR

| License | File |
|---------|------|
| MIT    | <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/a.c">hw/mcu/fake/a.c</a> |
| ?????  | <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a> |
| B      | <a href="https://github.com/apache/mynewt-core/blob/8552b65005101b9d318e3a9b371924807a1bb6e2/hw/mcu/fake/blinky.elf.bin">hw/mcu/fake/blinky.elf.bin</a> |
| GPL3   | <a href="https://github.com/apache/mynewt-core/blob/0dd19439c48d25e200518c5995273a44bd8e2d7c/hw/mcu/fake/c.c">hw/mcu/fake/c.c</a> |
| AL     | <a href="https://github.com/apache/mynewt-core/blob/8552b65005101b9d318e3a9b371924807a1bb6e2/hw/mcu/fake/d.c">hw/mcu/fake/d.c</a> |
| A      | <a href="https://github.com/apache/mynewt-core/blob/8552b65005101b9d318e3a9b371924807a1bb6e2/hw/mcu/fake/somebin.tar.gz">hw/mcu/fake/somebin.tar.gz</a> |
</details>

**Comment by utzig** [comment]
# RAT Report (2018-11-02 14:06:32)

# New files with unknown licenses

* <a href="https://github.com/apache/mynewt-core/blob/29bb8ad37f86b2af94b03bb275653d9e3e56944c/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a>

<details>
  <summary>Detailed analysis</summary>

# New files in this PR

| License | File |
|---------|------|
| MIT    | <a href="https://github.com/apache/mynewt-core/blob/29bb8ad37f86b2af94b03bb275653d9e3e56944c/hw/mcu/fake/a.c">hw/mcu/fake/a.c</a> |
| ?????  | <a href="https://github.com/apache/mynewt-core/blob/29bb8ad37f86b2af94b03bb275653d9e3e56944c/hw/mcu/fake/b.c">hw/mcu/fake/b.c</a> |
| B      | <a href="https://github.com/apache/mynewt-core/blob/0b78488c24ab81d68f5512c531e57b7574dbce32/hw/mcu/fake/blinky.elf.bin">hw/mcu/fake/blinky.elf.bin</a> |
| GPL3   | <a href="https://github.com/apache/mynewt-core/blob/29bb8ad37f86b2af94b03bb275653d9e3e56944c/hw/mcu/fake/c.c">hw/mcu/fake/c.c</a> |
| AL     | <a href="https://github.com/apache/mynewt-core/blob/0b78488c24ab81d68f5512c531e57b7574dbce32/hw/mcu/fake/d.c">hw/mcu/fake/d.c</a> |
| A      | <a href="https://github.com/apache/mynewt-core/blob/0b78488c24ab81d68f5512c531e57b7574dbce32/hw/mcu/fake/somebin.tar.gz">hw/mcu/fake/somebin.tar.gz</a> |
</details>

**Comment by utzig** [comment]
Reverted back to using `runtimeco/mynewt-travis-ci`, will wait build and merge!

**Pull request merged**
