### PR TITLE
Merge bsnbranch

### PR DESCRIPTION
**Pull request by wes3**

### CODE REVIEW

**Comment by wes3** [comment]
DO NOT MERGE YET! Need to commit more changes.

**Comment by wes3** [comment]
OK, I think it is ready for merging now.

**Comment by michal-narajowski** [comment]
Hi, Will

I tried to test to test bsncent + bsnprph, but encountered some issues:

When bsnprph starts:
```
000000 [ts=0ssb, mod=4 level=1] GAP procedure initiated: advertise; disc_mode=2 direct_addr_type=0 direct_addr=00:09:09:09:0b:0a adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
000169 [ts=1320292ssb, mod=64 level=1] adv complete
000170 [ts=1328104ssb, mod=64 level=3] error setting advertisement data; rc=530
```

bsncent starts ok, but when I power on a peripheral, bsncent crashes on an assert:

```
005126 --
005126        0 connections
005126        0 packets received
005127        0 bytes received
005852 Assert @ 0xc3cb
005852 Unhandled interrupt (2), exception sp 0x200012f0
005852  r0:0x00000000  r1:0x00000000  r2:0x80000000  r3:0xe000ed00
005852  r4:0x0000c3cb  r5:0x2000138c  r6:0x0000c401  r7:0x00000000
005852  r8:0x00000000  r9:0x00000000 r10:0x00000000 r11:0x00000000
005852 r12:0x00000004  lr:0x0000cca9  pc:0x0000ccb8 psr:0x61000000
005852 ICSR:0x00421802 HFSR:0x00000000 CFSR:0x00000000
005852 BFAR:0xe000ed38 MMFAR:0xe000ed34
```

I made no changes to syscfgs.

BR,
Michał Narajowski

**Comment by wes3** [comment]
Thanks for testing this. I will take a look and see what is going on.

**Comment by ccollins476ad** [comment]
The problem seems to be corruption of the `peer_chr_pool` mempool.  The corruption occurs in `ble_ll_scan_sm_start()` here:

```
    if (scansm->next_phy != scansm->cur_phy) {
        scansm->phy_data[scansm->next_phy].scan_chan = BLE_PHY_ADV_CHAN_START;
    }
```

```
(gdb) p scansm->next_phy
$5 = 255 '\377'
```

I don't know this code at all, so my apologies if I have gotten something wrong.  It appears `phy_data` is a 1- or 2-element array, so this is an out of bounds write.  It seems `next_phy` is set to `PHY_NOT_CONFIGURED`; maybe this bit of code needs to check for this special value?

**Comment by wes3** [comment]
Thanks Chris. I took a look at the code and it seems to me that this is an expected case so next_phy should be checked for NOT_CONFIGURED as you suggest. I also looked at other calls to ble_ll_scan_sm_start() and I think that a check of cur_phy should be made as well, although this one should maybe be an assert().

**Comment by andrzej-kaczmarek** [comment]
I'll fix this next_phy thing in separate PR since this is a general issue, not something broken by this PR.

**Comment by sjanc** [comment]
test this please

**Pull request merged**
