### PR TITLE
Adding bsp and mcu packages for dialog_da14695-dk-usb

### PR DESCRIPTION
**Pull request by mlaz**
This commit adds support for [DA14695 Development Kit – USB](https://www.dialog-semiconductor.com/products/da14695-development-kit-usb).

Everything works except the download script which fails to load images into QSPI flash when the board is running the factory firmware. A simple workaround is to erase QSPI flash using otp_tool or the manufacturer's flash application before running newt load.

### CODE REVIEW

**Comment by andrzej-kaczmarek** [comment]
Overall this looks good, although I'd consider moving scripts to some common package [1] since there's quite a lot of code there which will soon go out of sync between BSPs. also common syscfg `BOOT_*` defs could be included by `$import` in such case. I'd like to know what other think about this way of reusing code in BSPs since we do do this for other vendors.

[1] I see two reasonable ways of doing this: simply create `hw/bsp/dialog_common` package or move all dialog code to `hw/bsp/dialog`, e.g. `hw/bsp/dialog/common`, `hw/bsp/dialog/da1469x-dk-pro` etc.

**Comment by sjanc** [comment]
yes, we have way too many copies (with subtle changes) of nrf startup code around ...

**Comment by kasjer** [comment]
@mlaz are you going to merge this PR or some more work is needed?

**Comment by kasjer** [comment]
@mlaz I took liberty to update your PR (rebase and scripts moved to different place) just to move things forward.
Changes moved scripts to different place, I tested basic functionality download/debug, also new serial download path.
What I did not tested due to lack of knowledge is OTP part that was also moved.
@agross-korg could you please take a look again just to make sure that moving scripts did not break anything in your opinion.

@mlaz thanks for PR and I apologize for trading on your turf, I hope you don't mind.

**Comment by agross-korg** [comment]
> @mlaz I took liberty to update your PR (rebase and scripts moved to different place) just to move things forward. Changes moved scripts to different place, I tested basic functionality download/debug, also new serial download path. What I did not tested due to lack of knowledge is OTP part that was also moved. @agross-korg could you please take a look again just to make sure that moving scripts did not break anything in your opinion.
> 
> @mlaz thanks for PR and I apologize for trading on your turf, I hope you don't mind.

I don't see a problem with moving those scripts.

**Review by agross-korg — APPROVED** [review]

**Review by andrzej-kaczmarek — APPROVED** [review]

**Pull request merged**
