### PR TITLE
mcu/nordic: Update NRFX to version 3.8.0

### PR DESCRIPTION
**Pull request by sjanc**
https://github.com/NordicSemiconductor/nrfx/releases/tag/v3.8.0

### CODE REVIEW

**Comment by sjanc** [comment]
#AutoPTS run mynewt GAP/CON

**Review by kasjer — APPROVED** [review]

**Review by andrzej-kaczmarek — APPROVED** [review]

**Comment by sjanc** [comment]
#AutoPTS run mynewt GAP/CON

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/apache/mynewt-core/pull/3328#issuecomment-2444366407, board: nrf52, estimated start time: 15:05:50, test case count: 32, estimated duration: 0:12:53<details><summary>Test cases to be run</summary>GAP/CONN/NCON/BV-01-C<br>GAP/CONN/NCON/BV-02-C<br>GAP/CONN/NCON/BV-03-C<br>GAP/CONN/DCON/BV-01-C<br>GAP/CONN/UCON/BV-01-C<br>GAP/CONN/UCON/BV-02-C<br>GAP/CONN/UCON/BV-03-C<br>GAP/CONN/UCON/BV-06-C<br>GAP/CONN/ACEP/BV-01-C<br>GAP/CONN/ACEP/BV-03-C<br>GAP/CONN/ACEP/BV-04-C<br>GAP/CONN/GCEP/BV-01-C<br>GAP/CONN/GCEP/BV-02-C<br>GAP/CONN/GCEP/BV-05-C<br>GAP/CONN/GCEP/BV-06-C<br>GAP/CONN/SCEP/BV-01-C<br>GAP/CONN/SCEP/BV-03-C<br>GAP/CONN/DCEP/BV-01-C<br>GAP/CONN/DCEP/BV-03-C<br>GAP/CONN/DCEP/BV-05-C<br>GAP/CONN/DCEP/BV-06-C<br>GAP/CONN/CPUP/BV-01-C<br>GAP/CONN/CPUP/BV-02-C<br>GAP/CONN/CPUP/BV-03-C<br>GAP/CONN/CPUP/BV-04-C<br>GAP/CONN/CPUP/BV-05-C<br>GAP/CONN/CPUP/BV-06-C<br>GAP/CONN/CPUP/BV-08-C<br>GAP/CONN/CPUP/BV-10-C<br>GAP/CONN/TERM/BV-01-C<br>GAP/CONN/PRDA/BV-01-C<br>GAP/CONN/PRDA/BV-02-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests (32)</summary>GAP     GAP/CONN/ACEP/BV-01-C           PASS<br>GAP     GAP/CONN/ACEP/BV-03-C           PASS<br>GAP     GAP/CONN/ACEP/BV-04-C           PASS<br>GAP     GAP/CONN/CPUP/BV-01-C           PASS<br>GAP     GAP/CONN/CPUP/BV-02-C           PASS<br>GAP     GAP/CONN/CPUP/BV-03-C           PASS<br>GAP     GAP/CONN/CPUP/BV-04-C           PASS<br>GAP     GAP/CONN/CPUP/BV-05-C           PASS<br>GAP     GAP/CONN/CPUP/BV-06-C           PASS<br>GAP     GAP/CONN/CPUP/BV-08-C           PASS<br>GAP     GAP/CONN/CPUP/BV-10-C           PASS<br>GAP     GAP/CONN/DCEP/BV-01-C           PASS<br>GAP     GAP/CONN/DCEP/BV-03-C           PASS<br>GAP     GAP/CONN/DCEP/BV-05-C           PASS<br>GAP     GAP/CONN/DCEP/BV-06-C           PASS<br>GAP     GAP/CONN/DCON/BV-01-C           PASS<br>GAP     GAP/CONN/GCEP/BV-01-C           PASS<br>GAP     GAP/CONN/GCEP/BV-02-C           PASS<br>GAP     GAP/CONN/GCEP/BV-05-C           PASS (2)<br>GAP     GAP/CONN/GCEP/BV-06-C           PASS<br>GAP     GAP/CONN/NCON/BV-01-C           PASS<br>GAP     GAP/CONN/NCON/BV-02-C           PASS<br>GAP     GAP/CONN/NCON/BV-03-C           PASS<br>GAP     GAP/CONN/PRDA/BV-01-C           PASS<br>GAP     GAP/CONN/PRDA/BV-02-C           PASS<br>GAP     GAP/CONN/SCEP/BV-01-C           PASS<br>GAP     GAP/CONN/SCEP/BV-03-C           PASS<br>GAP     GAP/CONN/TERM/BV-01-C           PASS<br>GAP     GAP/CONN/UCON/BV-01-C           PASS<br>GAP     GAP/CONN/UCON/BV-02-C           PASS<br>GAP     GAP/CONN/UCON/BV-03-C           PASS<br>GAP     GAP/CONN/UCON/BV-06-C           PASS</details>

**Comment by sjanc** [comment]
#AutoPTS run mynewt nrf53 SM

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/apache/mynewt-core/pull/3328#issuecomment-2444560719, board: nrf53, estimated start time: 16:16:07, test case count: 61, estimated duration: 0:27:30<details><summary>Test cases to be run</summary>SM/CEN/PROT/BV-01-C<br>SM/CEN/JW/BV-05-C<br>SM/CEN/JW/BI-04-C<br>SM/CEN/JW/BI-01-C<br>SM/CEN/PKE/BV-01-C<br>SM/CEN/PKE/BV-04-C<br>SM/CEN/PKE/BI-01-C<br>SM/CEN/PKE/BI-02-C<br>SM/CEN/OOB/BV-01-C<br>SM/CEN/OOB/BV-03-C<br>SM/CEN/OOB/BV-09-C<br>SM/CEN/OOB/BI-01-C<br>SM/CEN/EKS/BV-01-C<br>SM/CEN/EKS/BI-01-C<br>SM/CEN/KDU/BV-05-C<br>SM/CEN/KDU/BV-06-C<br>SM/CEN/KDU/BV-10-C<br>SM/CEN/PIS/BV-02-C<br>SM/CEN/PIS/BV-03-C<br>SM/CEN/SCJW/BV-01-C<br>SM/CEN/SCJW/BV-04-C<br>SM/CEN/SCJW/BI-01-C<br>SM/CEN/SCPK/BV-01-C<br>SM/CEN/SCPK/BV-04-C<br>SM/CEN/SCPK/BI-01-C<br>SM/CEN/SCPK/BI-02-C<br>SM/CEN/SCOB/BV-01-C<br>SM/CEN/SCOB/BV-04-C<br>SM/CEN/SCOB/BI-01-C<br>SM/CEN/SCOB/BI-04-C<br>SM/PER/PROT/BV-02-C<br>SM/PER/JW/BV-02-C<br>SM/PER/JW/BI-03-C<br>SM/PER/JW/BI-02-C<br>SM/PER/PKE/BV-02-C<br>SM/PER/PKE/BV-05-C<br>SM/PER/PKE/BI-03-C<br>SM/PER/OOB/BV-02-C<br>SM/PER/OOB/BV-04-C<br>SM/PER/OOB/BV-10-C<br>SM/PER/OOB/BI-02-C<br>SM/PER/EKS/BV-02-C<br>SM/PER/EKS/BI-02-C<br>SM/PER/KDU/BV-01-C<br>SM/PER/KDU/BV-02-C<br>SM/PER/KDU/BV-07-C<br>SM/PER/KDU/BV-08-C<br>SM/PER/KDU/BI-04-C<br>SM/PER/PIS/BV-01-C<br>SM/PER/PIS/BV-02-C<br>SM/PER/SCJW/BV-02-C<br>SM/PER/SCJW/BV-03-C<br>SM/PER/SCJW/BI-02-C<br>SM/PER/SCPK/BV-02-C<br>SM/PER/SCPK/BV-03-C<br>SM/PER/SCPK/BI-03-C<br>SM/PER/SCPK/BI-04-C<br>SM/PER/SCOB/BV-02-C<br>SM/PER/SCOB/BV-03-C<br>SM/PER/SCOB/BI-02-C<br>SM/PER/SCOB/BI-03-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests (61)</summary>SM      SM/CEN/EKS/BI-01-C              PASS<br>SM      SM/CEN/EKS/BV-01-C              PASS<br>SM      SM/CEN/JW/BI-01-C               PASS<br>SM      SM/CEN/JW/BI-04-C               PASS<br>SM      SM/CEN/JW/BV-05-C               PASS<br>SM      SM/CEN/KDU/BV-05-C              PASS<br>SM      SM/CEN/KDU/BV-06-C              PASS<br>SM      SM/CEN/KDU/BV-10-C              PASS<br>SM      SM/CEN/OOB/BI-01-C              PASS<br>SM      SM/CEN/OOB/BV-01-C              PASS<br>SM      SM/CEN/OOB/BV-03-C              PASS<br>SM      SM/CEN/OOB/BV-09-C              PASS<br>SM      SM/CEN/PIS/BV-02-C              PASS<br>SM      SM/CEN/PIS/BV-03-C              PASS<br>SM      SM/CEN/PKE/BI-01-C              PASS<br>SM      SM/CEN/PKE/BI-02-C              PASS<br>SM      SM/CEN/PKE/BV-01-C              PASS<br>SM      SM/CEN/PKE/BV-04-C              PASS<br>SM      SM/CEN/PROT/BV-01-C             PASS<br>SM      SM/CEN/SCJW/BI-01-C             PASS<br>SM      SM/CEN/SCJW/BV-01-C             PASS<br>SM      SM/CEN/SCJW/BV-04-C             PASS<br>SM      SM/CEN/SCOB/BI-01-C             PASS<br>SM      SM/CEN/SCOB/BI-04-C             PASS<br>SM      SM/CEN/SCOB/BV-01-C             PASS<br>SM      SM/CEN/SCOB/BV-04-C             PASS<br>SM      SM/CEN/SCPK/BI-01-C             PASS<br>SM      SM/CEN/SCPK/BI-02-C             PASS<br>SM      SM/CEN/SCPK/BV-01-C             PASS<br>SM      SM/CEN/SCPK/BV-04-C             PASS<br>SM      SM/PER/EKS/BI-02-C              PASS<br>SM      SM/PER/EKS/BV-02-C              PASS<br>SM      SM/PER/JW/BI-02-C               PASS<br>SM      SM/PER/JW/BI-03-C               PASS<br>SM      SM/PER/JW/BV-02-C               PASS<br>SM      SM/PER/KDU/BI-04-C              PASS<br>SM      SM/PER/KDU/BV-01-C              PASS<br>SM      SM/PER/KDU/BV-02-C              PASS<br>SM      SM/PER/KDU/BV-07-C              PASS<br>SM      SM/PER/KDU/BV-08-C              PASS<br>SM      SM/PER/OOB/BI-02-C              PASS<br>SM      SM/PER/OOB/BV-02-C              PASS<br>SM      SM/PER/OOB/BV-04-C              PASS<br>SM      SM/PER/OOB/BV-10-C              PASS<br>SM      SM/PER/PIS/BV-01-C              PASS<br>SM      SM/PER/PIS/BV-02-C              PASS<br>SM      SM/PER/PKE/BI-03-C              PASS<br>SM      SM/PER/PKE/BV-02-C              PASS<br>SM      SM/PER/PKE/BV-05-C              PASS<br>SM      SM/PER/PROT/BV-02-C             PASS<br>SM      SM/PER/SCJW/BI-02-C             PASS<br>SM      SM/PER/SCJW/BV-02-C             PASS<br>SM      SM/PER/SCJW/BV-03-C             PASS<br>SM      SM/PER/SCOB/BI-02-C             PASS<br>SM      SM/PER/SCOB/BI-03-C             PASS<br>SM      SM/PER/SCOB/BV-02-C             PASS<br>SM      SM/PER/SCOB/BV-03-C             PASS<br>SM      SM/PER/SCPK/BI-03-C             PASS<br>SM      SM/PER/SCPK/BI-04-C             PASS<br>SM      SM/PER/SCPK/BV-02-C             PASS<br>SM      SM/PER/SCPK/BV-03-C             PASS</details>

**Pull request merged**
