### PR TITLE
Fix issues with logs, stats, console, reboot_log while stubbing and use req_apis for sensor drivers logs and stats

### PR DESCRIPTION
**Pull request by vrahane**
- Also fixing some build errors in mpu6050

- Stats and logs fix : Fix issues with logs, stats, console, reboot_log while stubbing and use req_apis for sensor drivers logs and stats

- MYNEWT-571
    sys/log/stub is incomplete or doesnt work with deep defines of
    reboot_log
    
- MYNEWT-847
    sys/console/stub broken
    
- MYNEWT-848
    sys/stats/stub broken
    
- MYNEWT-849
    Sensor drivers: remove syscfg for conditional compilation of logs and
    stats and use req_apis
    
- Also resolving any conflicts and unresolved dependencies

### CODE REVIEW

**Comment by mkiiskila** [comment]
Maybe the following instead:

pkg.req_apis:
    - log
    - stats

**Comment by vrahane** [comment]
Forgot that existed. Changing it. Thank you for the suggestion.

**Comment by vrahane** [comment]
@mkiiskila Can you please review it again, made a lot of changes and fixed all stubs :-)

**Comment by vrahane** [comment]
@ccollins476ad made changes as per review. Can you please take a look again.

**Pull request merged**
